# Generated by Django 5.2.5 on 2025-08-11 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_nested_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "user")},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes_count",
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
