# Generated by Django 4.2.9 on 2025-08-10 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', help_text='Who can see your profile', max_length=10)),
                ('default_post_privacy', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', help_text='Default privacy for new posts', max_length=10)),
                ('allow_friend_requests', models.BooleanField(default=True, help_text='Allow others to send you friend requests')),
                ('show_email', models.BooleanField(default=False, help_text='Show email on your profile')),
                ('show_birth_date', models.BooleanField(default=True, help_text='Show birth date on your profile')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('notify_new_posts', models.BooleanField(default=True, help_text='Get notified when friends post')),
                ('notify_comments', models.BooleanField(default=True, help_text='Get notified when someone comments on your posts')),
                ('notify_likes', models.BooleanField(default=True, help_text='Get notified when someone likes your posts')),
                ('notify_friend_requests', models.BooleanField(default=True, help_text='Get notified of new friend requests')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Enable two-factor authentication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
