# Generated by Django 4.2.9 on 2025-08-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_comments',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_likes',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_new_posts',
        ),
    ]
