# Generated by Django 4.2.9 on 2025-08-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_settings", "0002_remove_notification_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="two_factor_enabled",
        ),
    ]
