# Generated by Django 4.2.9 on 2025-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome Email"),
                    ("password_reset", "Password Reset"),
                    ("email_verification", "Email Verification"),
                    ("notification", "Notification Email"),
                    ("friend_request", "Friend Request"),
                    ("friend_request_accepted", "Friend Request Accepted"),
                ],
                max_length=30,
            ),
        ),
    ]
